#Manifesto Inicial

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: fabricioveronez/simulador-do-caos
        ports:
        - containerPort: 3000
        # resources:
        #   requests:
        #     cpu: 500m
        #     memory: 512Mi
        #   limits:
        #     cpu: 500m
        #     memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: web
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    name: http
    protocol: TCP
    nodePort: 30000