FROM cgr.dev/chainguard/node
ENV NODE_ENV=production
WORKDIR /app
COPY --chown=node:node package*.json ./
RUN npm install
COPY --chown=node:node . .
EXPOSE 8080
CMD ["server.js"]

# https://edu.chainguard.dev/chainguard/chainguard-images/getting-started/node/