# Stage 1 - Build
FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install --omit=dev

COPY . .

# Stage 2 - Runtime mínimo
FROM scratch

WORKDIR /app

# Copia o node runtime
COPY --from=builder /usr/local/bin/node /usr/local/bin/node

# Copia bibliotecas necessárias
COPY --from=builder /usr/lib /usr/lib
COPY --from=builder /lib /lib

# Copia aplicação
COPY --from=builder /app /app

EXPOSE 8080

CMD ["/usr/local/bin/node", "server.js"]