apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao
spec:
  selector:
    matchLabels:
      app: conversao
  template:
    metadata:
      labels:
        app: conversao
        # para remover o taint 
    spec:
      tolerations:           # 👈 COLOCA AQUI
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
          
      containers:
        - name: conversao
          image: kubedevio/conversao-temperatura:v1
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: conversao
spec:
  selector:
    app: conversao
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      name: http
      protocol: TCP
      nodePort: 30000
