---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-env
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-env
  template:
    metadata:
      labels:
        app: app-env
    spec:
      #remove taint
      # tolerations:        
      #   - key: "node-role.kubernetes.io/control-plane"
      #     operator: "Exists"
      #     effect: "NoSchedule"

      containers:
        - name: app-env
          image: kubedevio/app-variaveis-ambiente:v1
          ports:
          - containerPort: 3000
          # variaveis de ambiente definidas a partir do secret
          envFrom:
          - secretRef:
              name: app-secret

          # variaveis de ambiente definidas a partir do configmap
          # envFrom:
          #   - configMapRef:
          #       name: app-config

          # variaveis de ambiente definidas diretamente no deployment
          # env:
          # - name: APP_NAME
          #   value: "APP -K8S"
          # - name: APP_VERSION
          #   value: "2.0"  
          # - name: APP_AUTHOR
          #   value: "Danilo"                        
---
apiVersion: v1
kind: Service
metadata:
  name: app-env
spec:
  selector:
    app: app-env
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      name: http
      protocol: TCP
      nodePort: 30000
